from setuptools import setup

setup(
    name='QueueStatus',
    version='1.0',
    packages=['Lib.site-packages.PIL', 'Lib.site-packages.past', 'Lib.site-packages.past.tests',
              'Lib.site-packages.past.types', 'Lib.site-packages.past.utils', 'Lib.site-packages.past.builtins',
              'Lib.site-packages.past.translation', 'Lib.site-packages.xlrd', 'Lib.site-packages.xlwt',
              'Lib.site-packages.isapi', 'Lib.site-packages.future', 'Lib.site-packages.future.moves',
              'Lib.site-packages.future.moves.dbm', 'Lib.site-packages.future.moves.html',
              'Lib.site-packages.future.moves.http', 'Lib.site-packages.future.moves.test',
              'Lib.site-packages.future.moves.urllib', 'Lib.site-packages.future.moves.xmlrpc',
              'Lib.site-packages.future.moves.tkinter', 'Lib.site-packages.future.tests',
              'Lib.site-packages.future.types', 'Lib.site-packages.future.utils', 'Lib.site-packages.future.builtins',
              'Lib.site-packages.future.backports', 'Lib.site-packages.future.backports.html',
              'Lib.site-packages.future.backports.http', 'Lib.site-packages.future.backports.test',
              'Lib.site-packages.future.backports.email', 'Lib.site-packages.future.backports.email.mime',
              'Lib.site-packages.future.backports.urllib', 'Lib.site-packages.future.backports.xmlrpc',
              'Lib.site-packages.future.standard_library', 'Lib.site-packages.adodbapi', 'Lib.site-packages.altgraph',
              'Lib.site-packages.macholib', 'Lib.site-packages.win32com', 'Lib.site-packages.win32com.test',
              'Lib.site-packages.win32com.demos', 'Lib.site-packages.win32com.client',
              'Lib.site-packages.win32com.makegw', 'Lib.site-packages.win32com.server',
              'Lib.site-packages.win32com.servers', 'Lib.site-packages.ordlookup', 'Lib.site-packages.pythonwin.pywin',
              'Lib.site-packages.pythonwin.pywin.mfc', 'Lib.site-packages.pythonwin.pywin.idle',
              'Lib.site-packages.pythonwin.pywin.Demos.ocx', 'Lib.site-packages.pythonwin.pywin.tools',
              'Lib.site-packages.pythonwin.pywin.dialogs', 'Lib.site-packages.pythonwin.pywin.docking',
              'Lib.site-packages.pythonwin.pywin.debugger', 'Lib.site-packages.pythonwin.pywin.framework',
              'Lib.site-packages.pythonwin.pywin.framework.editor',
              'Lib.site-packages.pythonwin.pywin.framework.editor.color', 'Lib.site-packages.pythonwin.pywin.scintilla',
              'Lib.site-packages.libfuturize', 'Lib.site-packages.libfuturize.fixes', 'Lib.site-packages.PyInstaller',
              'Lib.site-packages.PyInstaller.lib', 'Lib.site-packages.PyInstaller.lib.altgraph',
              'Lib.site-packages.PyInstaller.lib.modulegraph', 'Lib.site-packages.PyInstaller.hooks',
              'Lib.site-packages.PyInstaller.hooks.pre_find_module_path',
              'Lib.site-packages.PyInstaller.hooks.pre_safe_import_module', 'Lib.site-packages.PyInstaller.utils',
              'Lib.site-packages.PyInstaller.utils.hooks', 'Lib.site-packages.PyInstaller.utils.hooks.subproc',
              'Lib.site-packages.PyInstaller.utils.win32', 'Lib.site-packages.PyInstaller.utils.cliutils',
              'Lib.site-packages.PyInstaller.depend', 'Lib.site-packages.PyInstaller.loader',
              'Lib.site-packages.PyInstaller.loader.rthooks', 'Lib.site-packages.PyInstaller.archive',
              'Lib.site-packages.PyInstaller.building', 'Lib.site-packages.win32comext.adsi',
              'Lib.site-packages.win32comext.bits', 'Lib.site-packages.win32comext.mapi',
              'Lib.site-packages.win32comext.shell', 'Lib.site-packages.win32comext.axdebug',
              'Lib.site-packages.win32comext.ifilter', 'Lib.site-packages.win32comext.propsys',
              'Lib.site-packages.win32comext.axscript', 'Lib.site-packages.win32comext.axscript.client',
              'Lib.site-packages.win32comext.axscript.server', 'Lib.site-packages.win32comext.internet',
              'Lib.site-packages.win32comext.axcontrol', 'Lib.site-packages.win32comext.directsound',
              'Lib.site-packages.win32comext.directsound.test', 'Lib.site-packages.win32comext.authorization',
              'Lib.site-packages.win32comext.taskscheduler', 'Lib.site-packages.libpasteurize',
              'Lib.site-packages.libpasteurize.fixes', 'Lib.site-packages.pip-10.0.1-py3.6.egg.pip',
              'Lib.site-packages.pip-10.0.1-py3.6.egg.pip._vendor',
              'Lib.site-packages.pip-10.0.1-py3.6.egg.pip._vendor.idna',
              'Lib.site-packages.pip-10.0.1-py3.6.egg.pip._vendor.pytoml',
              'Lib.site-packages.pip-10.0.1-py3.6.egg.pip._vendor.certifi',
              'Lib.site-packages.pip-10.0.1-py3.6.egg.pip._vendor.chardet',
              'Lib.site-packages.pip-10.0.1-py3.6.egg.pip._vendor.chardet.cli',
              'Lib.site-packages.pip-10.0.1-py3.6.egg.pip._vendor.distlib',
              'Lib.site-packages.pip-10.0.1-py3.6.egg.pip._vendor.distlib._backport',
              'Lib.site-packages.pip-10.0.1-py3.6.egg.pip._vendor.msgpack',
              'Lib.site-packages.pip-10.0.1-py3.6.egg.pip._vendor.urllib3',
              'Lib.site-packages.pip-10.0.1-py3.6.egg.pip._vendor.urllib3.util',
              'Lib.site-packages.pip-10.0.1-py3.6.egg.pip._vendor.urllib3.contrib',
              'Lib.site-packages.pip-10.0.1-py3.6.egg.pip._vendor.urllib3.contrib._securetransport',
              'Lib.site-packages.pip-10.0.1-py3.6.egg.pip._vendor.urllib3.packages',
              'Lib.site-packages.pip-10.0.1-py3.6.egg.pip._vendor.urllib3.packages.backports',
              'Lib.site-packages.pip-10.0.1-py3.6.egg.pip._vendor.urllib3.packages.ssl_match_hostname',
              'Lib.site-packages.pip-10.0.1-py3.6.egg.pip._vendor.colorama',
              'Lib.site-packages.pip-10.0.1-py3.6.egg.pip._vendor.html5lib',
              'Lib.site-packages.pip-10.0.1-py3.6.egg.pip._vendor.html5lib._trie',
              'Lib.site-packages.pip-10.0.1-py3.6.egg.pip._vendor.html5lib.filters',
              'Lib.site-packages.pip-10.0.1-py3.6.egg.pip._vendor.html5lib.treewalkers',
              'Lib.site-packages.pip-10.0.1-py3.6.egg.pip._vendor.html5lib.treeadapters',
              'Lib.site-packages.pip-10.0.1-py3.6.egg.pip._vendor.html5lib.treebuilders',
              'Lib.site-packages.pip-10.0.1-py3.6.egg.pip._vendor.lockfile',
              'Lib.site-packages.pip-10.0.1-py3.6.egg.pip._vendor.progress',
              'Lib.site-packages.pip-10.0.1-py3.6.egg.pip._vendor.requests',
              'Lib.site-packages.pip-10.0.1-py3.6.egg.pip._vendor.packaging',
              'Lib.site-packages.pip-10.0.1-py3.6.egg.pip._vendor.cachecontrol',
              'Lib.site-packages.pip-10.0.1-py3.6.egg.pip._vendor.cachecontrol.caches',
              'Lib.site-packages.pip-10.0.1-py3.6.egg.pip._vendor.webencodings',
              'Lib.site-packages.pip-10.0.1-py3.6.egg.pip._vendor.pkg_resources',
              'Lib.site-packages.pip-10.0.1-py3.6.egg.pip._internal',
              'Lib.site-packages.pip-10.0.1-py3.6.egg.pip._internal.req',
              'Lib.site-packages.pip-10.0.1-py3.6.egg.pip._internal.vcs',
              'Lib.site-packages.pip-10.0.1-py3.6.egg.pip._internal.utils',
              'Lib.site-packages.pip-10.0.1-py3.6.egg.pip._internal.models',
              'Lib.site-packages.pip-10.0.1-py3.6.egg.pip._internal.commands',
              'Lib.site-packages.pip-10.0.1-py3.6.egg.pip._internal.operations'],
    url='',
    license='',
    author='vodafone',
    author_email='',
    description='queueStatus tool'
)
